### ISSUE TITLE
Bower version and tag mismatch

### ISSUE THREAD

**Issue by p0lax** [bankrot/cadesplugin#1]
Just installed via bower to the latest tag v0.0.2 and bower said this:-
"bower cadesplugin#\* mismatch Version declared in the json (0.0.1) is different than the resolved one (0.0.2)"

I think bower.json has incorrect version tag.

**Comment by bankrot** [comment]
Sorry. It fixed. New version 0.0.3

**Comment by p0lax** [comment]
Thank you)
